require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .*/**/*
    - vendor/**/*
    - bin/**/*

Lint/RedundantCopDisableDirective:
  Severity: error

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Metrics/AbcSize:
  Max: 59

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 9

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 58

Layout/LineLength:
  Max: 90
  Exclude:
    - 'Gemfile'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: false

Naming/FileName:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: "double_quotes"
  Exclude:
    - Gemfile

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/YodaCondition:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/NestedGroups:
  Max: 8

RSpec/ImplicitSubject:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - and

RSpec/MultipleMemoizedHelpers:
  Max: 15

Naming/MethodParameterName:
  AllowedNames:
    # These are the default allowed names, set by Rubocop
    - io
    - id
    # These are some custom names that we want to allow, since they aren't
    # uncommunicative - they're actually rather meaningful!
    - to
    - "_"
